version: '3'

networks:
  cluster2:
    driver: bridge
services:
  # second shard - runs on cluster2 network
  db-shard-2-core-1:
    image: neo4j:4.4-enterprise
    hostname: "db-shard-2-core-1"
    container_name: db-shard-2-core-1
    ports:
      - "37480:7474"
      - "37481:7687"
    environment:
      NEO4J_AUTH: neo4j/neo
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: "db-shard-2-core-1:5000,db-shard-2-core-2:5000,db-shard-2-core-3:5000"
      NEO4J_causal__clustering_expected__core__cluster__size: "3"
      NEO4J_dbms_connector_bolt_advertised__address: "db-shard-2-core-1:7687"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
    volumes:
      - "./cypher:/cypher"
    networks:
      - cluster2

  db-shard-2-core-2:
    image: neo4j:4.4-enterprise
    hostname: "db-shard-2-core-2"
    container_name: db-shard-2-core-2
    ports:
      - "37482:7474"
      - "37483:7687"
    environment:
      NEO4J_AUTH: neo4j/neo
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: "db-shard-2-core-1:5000,db-shard-2-core-2:5000,db-shard-2-core-3:5000"
      NEO4J_causal__clustering_expected__core__cluster__size: "3"
      NEO4J_dbms_connector_bolt_advertised__address: "db-shard-2-core-2:7687"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
    volumes:
      - "./cypher:/cypher"
    networks:
      # This network is defined in docker-compose-main.yaml
      - cluster2

  db-shard-2-core-3:
    image: neo4j:4.4-enterprise
    hostname: "db-shard-2-core-3"
    container_name: db-shard-2-core-3
    ports:
      - "37484:7474"
      - "37485:7687"
    environment:
      NEO4J_AUTH: neo4j/neo
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: "db-shard-2-core-1:5000,db-shard-2-core-2:5000,db-shard-2-core-3:5000"
      NEO4J_causal__clustering_expected__core__cluster__size: "3"
      NEO4J_dbms_connector_bolt_advertised__address: "db-shard-2-core-3:7687"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
    volumes:
      - "./cypher:/cypher"
    networks:
      # This network is defined in docker-compose-main.yaml
      - cluster2
