version: '3'

networks:
    cluster1:
        driver: bridge
    cluster2:
        driver: bridge
    cluster3:
        driver: bridge
    app-network:
        driver: bridge

services:
    proxy:
        image: neo4j:4.4-enterprise
        hostname: proxy
        container_name: proxy
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_fabric_database_name: fabric

            NEO4J_fabric_graph_0_name: dbshard1
            NEO4J_fabric_graph_0_uri: neo4j://db-shard-1-core-1:7687,neo4j://db-shard-1-core-2:7687,neo4j://db-shard-1-core-3:7687

            NEO4J_fabric_graph_1_name: dbshard2
            NEO4J_fabric_graph_1_uri: neo4j://db-shard-2-core-1:7687,neo4j://db-shard-2-core-2:7687,neo4j://db-shard-2-core-3:7687

            NEO4J_fabric_graph_2_name: dbshard3
            NEO4J_fabric_graph_2_uri: neo4j://db-shard-3-core-1:7687,neo4j://db-shard-3-core-2:7687,neo4j://db-shard-3-core-3:7687

            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}

        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        networks:
            - cluster1
            - cluster2
            - cluster3

    # first shard - runs on cluster1 network
    db-shard-1-core-1:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-1-core-1"
        container_name: db-shard-1-core-1
        ports:
            - "37474:7474"
            - "37687:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE

            NEO4J_causal__clustering_initial__discovery__members: "db-shard-1-core-1:5000,db-shard-1-core-2:5000,db-shard-1-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"

            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-1-core-1:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster1

    db-shard-1-core-2:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-1-core-2"
        container_name: db-shard-1-core-2
        ports:
            - "47474:7474"
            - "47687:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE
            NEO4J_causal__clustering_initial__discovery__members: "db-shard-1-core-1:5000,db-shard-1-core-2:5000,db-shard-1-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"
            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-1-core-2:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster1

    db-shard-1-core-3:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-1-core-3"
        container_name: db-shard-1-core-3
        ports:
            - "4100:7474"
            - "57540:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE
            NEO4J_causal__clustering_initial__discovery__members: "db-shard-1-core-1:5000,db-shard-1-core-2:5000,db-shard-1-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"
            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-1-core-3:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster1

    # second shard - runs on cluster2 network
    db-shard-2-core-1:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-2-core-1"
        container_name: db-shard-2-core-1
        ports:
            - "37480:7474"
            - "37481:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE

            NEO4J_causal__clustering_initial__discovery__members: "db-shard-2-core-1:5000,db-shard-2-core-2:5000,db-shard-2-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"
            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-2-core-1:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster2

    db-shard-2-core-2:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-2-core-2"
        container_name: db-shard-2-core-2
        ports:
            - "37482:7474"
            - "37483:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE
            NEO4J_causal__clustering_initial__discovery__members: "db-shard-2-core-1:5000,db-shard-2-core-2:5000,db-shard-2-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"
            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-2-core-2:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster2

    db-shard-2-core-3:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-2-core-3"
        container_name: db-shard-2-core-3
        ports:
            - "37484:7474"
            - "37485:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE
            NEO4J_causal__clustering_initial__discovery__members: "db-shard-2-core-1:5000,db-shard-2-core-2:5000,db-shard-2-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"
            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-2-core-3:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster2

    # third shard - runs on cluster3 network
    db-shard-3-core-1:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-3-core-1"
        container_name: db-shard-3-core-1
        ports:
            - "37490:7474"
            - "37491:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE

            NEO4J_causal__clustering_initial__discovery__members: "db-shard-3-core-1:5000,db-shard-3-core-2:5000,db-shard-3-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"
            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-3-core-1:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster3

    db-shard-3-core-2:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-3-core-2"
        container_name: db-shard-3-core-2
        ports:
            - "37492:7474"
            - "37493:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE
            NEO4J_causal__clustering_initial__discovery__members: "db-shard-3-core-1:5000,db-shard-3-core-2:5000,db-shard-3-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"
            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-3-core-2:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster3

    db-shard-3-core-3:
        image: neo4j:4.4-enterprise
        hostname: "db-shard-3-core-3"
        container_name: db-shard-3-core-3
        ports:
            - "37494:7474"
            - "37495:7687"
        environment:
            NEO4J_AUTH: neo4j/neo
            NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
            NEO4J_dbms_mode: CORE
            NEO4J_causal__clustering_initial__discovery__members: "db-shard-3-core-1:5000,db-shard-3-core-2:5000,db-shard-3-core-3:5000"
            NEO4J_dbms_cluster_minimum__initial__system__primaries__count: "3"
            NEO4J_dbms_connector_bolt_advertised__address: "db-shard-3-core-3:7687"
            NEO4JLABS_PLUGINS: '["apoc"]'
            NEO4J_dbms_security_procedures_unrestricted: apoc.*
            NEO4J_dbms_security_procedures_allowlist: apoc.*
            NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
        healthcheck:
            test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo", "RETURN 1"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        volumes:
            - "./cypher:/cypher"
        networks:
            - cluster3

    # mqtt broker
    mqtt-broker:
        image: eclipse-mosquitto:2.0.15
        container_name: mosquitto-broker
        restart: unless-stopped
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./mqtt-broker/mosquitto/config:/mosquitto/config
            - ./mqtt-broker/mosquitto/data:/mosquitto/data
            - ./mqtt-broker/mosquitto/log:/mosquitto/log
        environment:
            - INITIAL_USER=admin
            - INITIAL_PASSWORD=admin
        entrypoint: |
            sh -c 'chown mosquitto:mosquitto /mosquitto/config/pwfile;
            if [ ! -s /mosquitto/config/pwfile ]; then
              mosquitto_passwd -b -c /mosquitto/config/pwfile $${INITIAL_USER} $${INITIAL_PASSWORD};
            fi;
            exec /docker-entrypoint.sh mosquitto -c /mosquitto/config/mosquitto.conf'
        healthcheck:
            test: ["CMD-SHELL", "mosquitto_pub -h localhost -t test -m 'health check' -u admin -P admin"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - app-network

    # Notification Service
    health-monitor:
        image: alpine:latest
        container_name: health-monitor
        depends_on:
            proxy:
                condition: service_healthy
            db-shard-1-core-1:
                condition: service_healthy
            db-shard-1-core-2:
                condition: service_healthy
            db-shard-1-core-3:
                condition: service_healthy
            db-shard-2-core-1:
                condition: service_healthy
            db-shard-2-core-2:
                condition: service_healthy
            db-shard-2-core-3:
                condition: service_healthy
            db-shard-3-core-1:
                condition: service_healthy
            db-shard-3-core-2:
                condition: service_healthy
            db-shard-3-core-3:
                condition: service_healthy
            mqtt-broker:
                condition: service_healthy
        command: |
            sh -c 'echo "All services are working successfully!";
            echo "Proxy: http://localhost:7474";
            echo "MQTT Broker: mqtt://localhost:1883";
            echo "Deployment ended at: $$(date)";
            sleep 10'
        networks:
            - app-network
