version: '3'

networks:
  cluster3:
    driver: bridge

services:
  # third shard - runs on cluster3 network
  db-shard-3-core-1:
    image: neo4j:4.4-enterprise
    hostname: "db-shard-3-core-1"
    container_name: db-shard-3-core-1
    ports:
      - "37490:7474"
      - "37491:7687"
    environment:
      NEO4J_AUTH: neo4j/neo
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: "db-shard-3-core-1:5000,db-shard-3-core-2:5000,db-shard-3-core-3:5000"
      NEO4J_causal__clustering_expected__core__cluster__size: "3"
      NEO4J_dbms_connector_bolt_advertised__address: "db-shard-3-core-1:7687"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
    volumes:
      - "./cypher:/cypher"
    networks:
      # This network is defined in docker-compose-main.yaml
      - cluster3

  db-shard-3-core-2:
    image: neo4j:4.4-enterprise
    hostname: "db-shard-3-core-2"
    container_name: db-shard-3-core-2
    ports:
      - "37492:7474"
      - "37493:7687"
    environment:
      NEO4J_AUTH: neo4j/neo
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: "db-shard-3-core-1:5000,db-shard-3-core-2:5000,db-shard-3-core-3:5000"
      NEO4J_causal__clustering_expected__core__cluster__size: "3"
      NEO4J_dbms_connector_bolt_advertised__address: "db-shard-3-core-2:7687"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
    volumes:
      - "./cypher:/cypher"
    networks:
      # This network is defined in docker-compose-main.yaml
      - cluster3

  db-shard-3-core-3:
    image: neo4j:4.4-enterprise
    hostname: "db-shard-3-core-3"
    container_name: db-shard-3-core-3
    ports:
      - "37494:7474"
      - "37495:7687"
    environment:
      NEO4J_AUTH: neo4j/neo
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_mode: CORE
      NEO4J_causal__clustering_initial__discovery__members: "db-shard-3-core-1:5000,db-shard-3-core-2:5000,db-shard-3-core-3:5000"
      NEO4J_causal__clustering_expected__core__cluster__size: "3"
      NEO4J_dbms_connector_bolt_advertised__address: "db-shard-3-core-3:7687"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_memory_heap_max__size: ${NEO4J_MAX_HEAP_SIZE:-1G}
    volumes:
      - "./cypher:/cypher"
    networks:
      # This network is defined in docker-compose-main.yaml
      - cluster3
