import cv2

SERVER_IP="localhost"
SERVER_PORT=9999
RESOLUTION=(1920, 1080)
FPS=15
CAMERA_INDEX=0
DISPLAY_LOCALLY=False
STREAM_DURATION_MINUTES=0
# for Windows
STREAMING_PROTOCOL=cv2.CAP_DSHOW

# for Linux
# STREAMING_PROTOCOL=cv2.CAP_V4L2 


# Opc-UA server configuration   
OPC_SERVER_HOST = "0.0.0.0"
OPC_SERVER_PORT = 4840
